"""
TruthLens AI - Streamlit Fake News Detection App

Run locally:
    streamlit run app.py
"""

from __future__ import annotations

import json
import string
from datetime import datetime
from pathlib import Path
import matplotlib.pyplot as plt

import joblib
import pandas as pd
import streamlit as st
from nltk.corpus import stopwords
from nltk.tokenize import wordpunct_tokenize
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS


BASE_DIR = Path(__file__).resolve().parent
MODEL_FILE = BASE_DIR / "model.pkl"
VECTORIZER_FILE = BASE_DIR / "vectorizer.pkl"
METRICS_FILE = BASE_DIR / "metrics.json"
HISTORY_FILE = BASE_DIR / "prediction_history.csv"


st.set_page_config(
    page_title="TruthLens AI",
    page_icon="TL",
    layout="wide",
    initial_sidebar_state="expanded",
)


def ensure_nltk_resources() -> None:
    """Kept for Colab/classroom readability; preprocessing works without downloads."""
    return None


def get_stop_words() -> set[str]:
    """Use NLTK stopwords when available, otherwise fall back to scikit-learn stopwords."""
    try:
        return set(stopwords.words("english"))
    except LookupError:
        return set(ENGLISH_STOP_WORDS)


@st.cache_resource
def load_artifacts():
    """Load the trained model and TF-IDF vectorizer once per Streamlit session."""
    if not MODEL_FILE.exists() or not VECTORIZER_FILE.exists():
        return None, None
    return joblib.load(MODEL_FILE), joblib.load(VECTORIZER_FILE)



def load_metrics() -> dict:
    """Load saved test metrics produced by train_model.py."""
    if METRICS_FILE.exists():
        return json.loads(METRICS_FILE.read_text(encoding="utf-8"))
    return {}


def preprocess_text(text: str) -> str:
    """Apply lowercasing, punctuation removal, tokenization, and stopword removal."""
    text = text.lower()
    text = text.translate(str.maketrans("", "", string.punctuation))
    tokens = wordpunct_tokenize(text)
    stop_words = get_stop_words()
    cleaned_tokens = [word for word in tokens if word.isalpha() and word not in stop_words]
    return " ".join(cleaned_tokens)


def predict_news(text: str, model, vectorizer) -> dict:
    """Predict whether news text is real or fake and return class probabilities."""
    cleaned_text = preprocess_text(text)
    transformed_text = vectorizer.transform([cleaned_text])
    prediction = int(model.predict(transformed_text)[0])

    if hasattr(model, "predict_proba"):
        probabilities = model.predict_proba(transformed_text)[0]
        fake_probability = float(probabilities[0])
        real_probability = float(probabilities[1])
    else:
        decision_score = float(model.decision_function(transformed_text)[0])
        real_probability = 1 / (1 + pow(2.71828, -decision_score))
        fake_probability = 1 - real_probability

    predicted_label = "Real" if prediction == 1 else "Fake"
    confidence = real_probability if prediction == 1 else fake_probability
    credibility = real_probability

    return {
        "label": predicted_label,
        "confidence": confidence,
        "credibility": credibility,
        "fake_probability": fake_probability,
        "real_probability": real_probability,
        "cleaned_text": cleaned_text,
    }


def save_history(news_text: str, result: dict) -> None:
    """Append the current prediction to a CSV history file."""
    row = {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "prediction": result["label"],
        "confidence_percent": round(result["confidence"] * 100, 2),
        "credibility_percent": round(result["credibility"] * 100, 2),
        "news_text": news_text[:500],
    }

    new_entry = pd.DataFrame([row])
    if HISTORY_FILE.exists():
        history = pd.read_csv(HISTORY_FILE)
        history = pd.concat([new_entry, history], ignore_index=True)
    else:
        history = new_entry
    history.to_csv(HISTORY_FILE, index=False)


def build_report(news_text: str, result: dict, metrics: dict) -> str:
    """Create a downloadable plain-text prediction report."""
    accuracy = metrics.get("accuracy")
    accuracy_text = f"{accuracy * 100:.2f}%" if isinstance(accuracy, (int, float)) else "Not available"

    return f"""TruthLens AI - Fake News Detection Report
Generated At: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

Prediction: {result["label"]} News
Confidence Score: {result["confidence"] * 100:.2f}%
News Credibility: {result["credibility"] * 100:.2f}%
Fake Probability: {result["fake_probability"] * 100:.2f}%
Real Probability: {result["real_probability"] * 100:.2f}%
Model Test Accuracy: {accuracy_text}

Input News:
{news_text}

Cleaned Text:
{result["cleaned_text"]}

Note:
This result is generated by a machine learning model and should support, not replace,
human fact-checking and verification from trusted sources.
"""


def inject_css() -> None:
    """Add a modern dark UI theme for the Streamlit application."""
    st.markdown(
        """
        <style>
        :root {
            --bg: #07111f;
            --panel: #101b2f;
            --panel-2: #16243b;
            --text: #f4f7fb;
            --muted: #9fb0c7;
            --cyan: #21d4fd;
            --green: #36d399;
            --red: #ff4d6d;
            --amber: #fbbf24;
        }

        .stApp {
            background:
                radial-gradient(circle at top left, rgba(33, 212, 253, 0.16), transparent 34rem),
                linear-gradient(135deg, #07111f 0%, #111827 55%, #121524 100%);
            color: var(--text);
        }

        section[data-testid="stSidebar"] {
            background: #0b1424;
            border-right: 1px solid rgba(255, 255, 255, 0.08);
        }

        .hero {
            padding: 2rem;
            border: 1px solid rgba(255, 255, 255, 0.08);
            border-radius: 8px;
            background: linear-gradient(135deg, rgba(33, 212, 253, 0.14), rgba(54, 211, 153, 0.08));
            box-shadow: 0 22px 70px rgba(0, 0, 0, 0.28);
        }

        .hero h1 {
            margin: 0 0 0.45rem 0;
            font-size: clamp(2rem, 5vw, 4rem);
            letter-spacing: 0;
            color: #ffffff;
        }

        .hero p {
            margin: 0;
            color: var(--muted);
            font-size: 1.05rem;
            max-width: 920px;
        }

        .result-card {
            border-radius: 8px;
            padding: 1.4rem;
            border: 1px solid rgba(255, 255, 255, 0.09);
            background: rgba(16, 27, 47, 0.9);
        }

        .real-card {
            border-left: 6px solid var(--green);
        }

        .fake-card {
            border-left: 6px solid var(--red);
        }

        .warning-banner {
            padding: 1rem 1.2rem;
            border-radius: 8px;
            background: rgba(255, 77, 109, 0.14);
            border: 1px solid rgba(255, 77, 109, 0.45);
            color: #ffd7df;
            font-weight: 700;
        }

        .success-banner {
            padding: 1rem 1.2rem;
            border-radius: 8px;
            background: rgba(54, 211, 153, 0.12);
            border: 1px solid rgba(54, 211, 153, 0.42);
            color: #cbffe9;
            font-weight: 700;
        }

        .metric-strip {
            display: grid;
            grid-template-columns: repeat(3, minmax(0, 1fr));
            gap: 1rem;
            margin-top: 1rem;
        }

        .mini-metric {
            padding: 1rem;
            border-radius: 8px;
            background: rgba(255, 255, 255, 0.055);
            border: 1px solid rgba(255, 255, 255, 0.08);
        }

        .mini-metric span {
            display: block;
            color: var(--muted);
            font-size: 0.85rem;
        }

        .mini-metric strong {
            display: block;
            color: #ffffff;
            font-size: 1.55rem;
            margin-top: 0.25rem;
        }

        div[data-testid="stMetricValue"] {
            color: #ffffff;
        }

        .stTextArea textarea {
            background: rgba(16, 27, 47, 0.92);
            color: #ffffff;
            border: 1px solid rgba(255, 255, 255, 0.14);
            border-radius: 8px;
        }

        .stButton button, .stDownloadButton button {
            border-radius: 8px;
            border: 1px solid rgba(33, 212, 253, 0.45);
            background: linear-gradient(135deg, #0ea5e9, #14b8a6);
            color: #ffffff;
            font-weight: 800;
        }

        @media (max-width: 780px) {
            .metric-strip {
                grid-template-columns: 1fr;
            }
            .hero {
                padding: 1.25rem;
            }
        }
        </style>
        """,
        unsafe_allow_html=True,
    )


def render_sidebar(metrics: dict) -> None:
    """Render project information and model metrics in the sidebar."""
    st.sidebar.title("TruthLens AI")
    st.sidebar.caption("Fast NLP fake news detection using TF-IDF and Logistic Regression.")

    accuracy = metrics.get("accuracy")
    if isinstance(accuracy, (int, float)):
        st.sidebar.metric("Test Accuracy", f"{accuracy * 100:.2f}%")
    else:
        st.sidebar.info("Train the model to show test accuracy.")

    st.sidebar.divider()
    st.sidebar.write("Pipeline")
    st.sidebar.write("1. Clean text")
    st.sidebar.write("2. Remove stopwords")
    st.sidebar.write("3. TF-IDF vectorization")
    st.sidebar.write("4. Logistic Regression")

    st.sidebar.divider()
    st.sidebar.warning("Always verify important news with trusted sources.")


def render_history() -> None:
    """Show recent prediction history if available."""
    st.subheader("Analysis History")
    if HISTORY_FILE.exists():
        history = pd.read_csv(HISTORY_FILE).head(10)
        st.dataframe(history, use_container_width=True, hide_index=True)
    else:
        st.caption("No predictions analyzed yet.")


def main() -> None:
    ensure_nltk_resources()
    inject_css()

    model, vectorizer = load_artifacts()
    metrics = load_metrics()
    render_sidebar(metrics)

    st.markdown(
        """
        <div class="hero">
            <h1>TruthLens AI</h1>
            <p>TruthLens AI - AI-Powered Fake News Detection and Credibility Analysis Platform. Enter a headline or full article and get a fast machine learning prediction with confidence and credibility scoring.</p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.write("")

    if model is None or vectorizer is None:
        st.error("Model files are missing. Run `python train_model.py` first.")
        st.stop()

    sample_news = {
        "Choose an example": "",
        "Real-style: official policy update": "The finance ministry announced a revised infrastructure investment plan after a cabinet meeting, according to an official press release.",
        "Real-style: science report": "Researchers published peer reviewed findings showing improved solar cell efficiency under controlled laboratory conditions.",
        "Fake-style: miracle cure": "A secret herb discovered by an anonymous doctor can cure every disease overnight without any medical treatment.",
        "Fake-style: conspiracy claim": "Leaked messages prove that world leaders have been replaced by identical robots, according to a viral anonymous blog.",
    }

    left_col, right_col = st.columns([1.35, 1])

    with left_col:
        st.subheader("Analyze News")
        selected_sample = st.selectbox("Sample news examples", list(sample_news.keys()))
        default_text = sample_news[selected_sample]
        news_text = st.text_area(
            "Enter a news headline or article",
            value=default_text,
            height=240,
            placeholder="Paste a news headline or article here...",
        )

        analyze_clicked = st.button("Analyze News", use_container_width=True)

    with right_col:
        st.subheader("Model Snapshot")
        total_samples = metrics.get("total_samples", "N/A")
        train_samples = metrics.get("train_samples", "N/A")
        test_samples = metrics.get("test_samples", "N/A")
        accuracy = metrics.get("accuracy")
        accuracy_display = f"{accuracy * 100:.2f}%" if isinstance(accuracy, (int, float)) else "N/A"

        st.markdown(
            f"""
            <div class="result-card">
                <div class="metric-strip">
                    <div class="mini-metric"><span>Accuracy</span><strong>{accuracy_display}</strong></div>
                    <div class="mini-metric"><span>Training Rows</span><strong>{train_samples}</strong></div>
                    <div class="mini-metric"><span>Test Rows</span><strong>{test_samples}</strong></div>
                </div>
                <div class="mini-metric" style="margin-top: 1rem;"><span>Total Dataset Rows</span><strong>{total_samples}</strong></div>
            </div>
            """,
            unsafe_allow_html=True,
        )

    if analyze_clicked:
        if not news_text.strip():
            st.warning("Please enter a headline or article before analyzing.")
        else:
            result = predict_news(news_text, model, vectorizer)
            save_history(news_text, result)

            st.write("")
            st.subheader("Prediction Result")

            card_class = "real-card" if result["label"] == "Real" else "fake-card"
            icon = "REAL" if result["label"] == "Real" else "FAKE"
            st.markdown(
                f"""
                <div class="result-card {card_class}">
                    <h2>{icon} News Detected</h2>
                    <div class="metric-strip">
                        <div class="mini-metric"><span>Prediction</span><strong>{result["label"]}</strong></div>
                        <div class="mini-metric"><span>Confidence</span><strong>{result["confidence"] * 100:.2f}%</strong></div>
                        <div class="mini-metric"><span>Credibility</span><strong>{result["credibility"] * 100:.2f}%</strong></div>
                    </div>
                </div>
                """,
                unsafe_allow_html=True,
            )
            st.subheader("News Credibility Score")

            credibility_score = result["credibility"] * 100

            st.metric(
                label="Credibility Score",
                value=f"{credibility_score:.2f}%"
            )

            st.subheader("Credibility Meter")

            score = result["credibility"] * 100

            if score >= 90:
             st.success(f"Very High Credibility ({score:.2f}%)")

            elif score >= 75:
             st.success(f"High Credibility ({score:.2f}%)")

            elif score >= 50:
             st.info(f"Moderate Credibility ({score:.2f}%)")

            else:
             st.warning(f"Low Credibility ({score:.2f}%)")

            st.subheader("Why This Prediction?")

            if result["label"] == "Real":
                st.success(
                    f"""
                    The article was classified as REAL because the writing style,
                    vocabulary, and sentence structure closely matched patterns
                    found in verified news articles from the training dataset.

                    Real Probability:
                    {result['real_probability']*100:.2f}%
                    """
                )

            else:
                st.error(
                    f"""
                    The article was classified as FAKE because the text contained
                    patterns commonly associated with misleading, sensational,
                    or unverified news content.

                    Fake Probability:
                    {result['fake_probability']*100:.2f}%
                    """
                )


            if result["label"] == "Fake":
                st.markdown(
                    '<div class="warning-banner">Fake News Warning: This content has patterns commonly associated with unreliable or misleading news. Verify before sharing.</div>',
                    unsafe_allow_html=True,
                )
            else:
                st.markdown(
                    '<div class="success-banner">Real News Signal: This content appears closer to verified news patterns in the trained dataset.</div>',
                    unsafe_allow_html=True,
                )

            progress_col_1, progress_col_2 = st.columns(2)
            with progress_col_1:
                st.write("Real Probability")
                st.progress(result["real_probability"])
            with progress_col_2:
                st.write("Fake Probability")
                st.progress(result["fake_probability"])

            report_text = build_report(news_text, result, metrics)
            st.download_button(
                "Download Prediction Report",
                data=report_text,
                file_name="truthlens_prediction_report.txt",
                mime="text/plain",
                use_container_width=True,
            )
            
           

    st.write("")
    render_history()


if __name__ == "__main__":
    main()
